export const LOGIN_SCENE = 'LOGIN_SCENE';
export const TRANSACTION_SELECT_SCENE = 'TRANSACTION_SELECT_SCENE';
export const TRANSACTION_ADD_SCENE = 'TRANSACTION_ADD_SCENE';
export const COMMENT_ADD_SCENE = 'COMMENT_ADD_SCENE';
